import type { Metadata } from "next";
import "./globals.css";

import { Lora, Nunito_Sans } from 'next/font/google';
import { Toaster } from "@/components/ui/toaster";

const lora = Lora({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lora'
})

const nunito_sans = Nunito_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-nunitosans'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lora.variable} ${nunito_sans.variable} antialiased`}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
